//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class empbasic
{
    public empbasic()
    {
        this.empdetails = new HashSet<empdetail>();
    }

    public int EmpID { get; set; }
    public string AssID { get; set; }
    public System.DateTime DOJ { get; set; }
    public string FName { get; set; }
    public string LName { get; set; }
    public string Gender { get; set; }
    public string Designation { get; set; }
    public int Status { get; set; }

    public virtual ICollection<empdetail> empdetails { get; set; }
}

public partial class empdetail
{
    public int EmpDetID { get; set; }
    public int EmpID { get; set; }
    public System.DateTime DOB { get; set; }
    public Nullable<System.DateTime> DOA { get; set; }
    public string SpousName { get; set; }
    public string MotherName { get; set; }
    public string FatherName { get; set; }
    public string Childrens { get; set; }
    public string BloodGroup { get; set; }
    public string PanNO { get; set; }
    public string PassPortNo { get; set; }
    public string RessAdds { get; set; }
    public string RessPin { get; set; }
    public string RessCity { get; set; }
    public string RessState { get; set; }
    public string RessCountry { get; set; }
    public string PermAdds { get; set; }
    public string PermPin { get; set; }
    public string PermCity { get; set; }
    public string PermState { get; set; }
    public string PermCountry { get; set; }
    public string Phone { get; set; }
    public string Mobile { get; set; }
    public string EmailOff { get; set; }
    public string EmailPerm { get; set; }
    public string BankAccNo { get; set; }
    public string BankName { get; set; }
    public string BankBranch { get; set; }
    public string BankIFSC { get; set; }
    public byte[] Photo { get; set; }

    public virtual empbasic empbasic { get; set; }
}

public partial class user
{
    public string UserName { get; set; }
    public string Password { get; set; }
    public string AssID { get; set; }
    public int Status { get; set; }
}
